### ISSUE TITLE
Could you make syntax coloring for JEdit?

### ISSUE THREAD

**Issue by ghost** [Joe7M/smallbasic.geany.syntaxcoloring#2]
JEdit has modes for `vbscript` and `visualbasic`. They could be used as the reference to make the `smallbasic` mode.

**Comment by Joe7M** [comment]
I had a look and it seems quite easy to do. Give me some time.

**Comment by Joe7M** [comment]
Enjoy and let me know if you have problems or found bugs.

https://github.com/Joe7M/smallbasic.jedit.syntaxcoloring/tree/main
